package io.customer.customerapi;

import javax.validation.Valid;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import io.customer.customerapi.services.CustomerService;
import io.customer.customerapi.swagger.api.CustomersApi;
import io.customer.customerapi.swagger.model.CreateCustomerResponse;
import io.customer.customerapi.swagger.model.Customer;

/**
 * Customer API REST Controller defining Create, Update, Delete etc Resources
 * for Customer management. The controller class implements CustomerApi
 * interface generated by Swagger maven plugin.
 * 
 * @author Viral Patel
 *
 */
@RestController
public class CustomerApiResource implements CustomersApi {

	private final CustomerService customerService;

	public CustomerApiResource(CustomerService customerService) {
		this.customerService = customerService;
	}

	@Override
	public ResponseEntity<CreateCustomerResponse> createCustomer(String correlationId,
			@Valid @RequestBody Customer customer) {

		String customerId = customerService.createCustomer(customer);

		return new ResponseEntity<>(new CreateCustomerResponse().id(customerId), HttpStatus.CREATED);
	}

	@Override
	public ResponseEntity<Void> updateCustomer(String customerId, @Valid @RequestBody Customer customer) {

		customerService.updateCustomer(customerId, customer);
		return new ResponseEntity<>(HttpStatus.OK);
	}

	@Override
	public ResponseEntity<Void> deleteCustomer(String customerId) {

		customerService.deleteCustomer(customerId);
		return new ResponseEntity<>(HttpStatus.OK);
	}
}
