= Customer API

The sample Customer API built using Spring Boot.

== Library used
1. Spring Boot 2.0.4.RELEASE
2. Swagger Annotation 1.5.17
3. Spring RESTDocs 2.0.2.RELEASE

== Installing

The API can be easily built with maven wapper. You also need JDK 1.8.

 $ ./mvnw clean install

== Features

=== Create customer

Create new customer record in Organisation CRM system.

*POST /customers*

.Sample request
[source,http,options="nowrap"]
----
POST /customers HTTP/1.1
Content-Type: application/json;charset=UTF-8
correlationId: 4a34dfd12
Host: localhost:8080
Content-Length: 382

{
  "firstName" : "John",
  "lastName" : "Doe",
  "dateOfBirth" : "1980-12-28",
  "emailAddress" : "johndoe@company.com",
  "postalAddresses" : [ {
    "addressType" : "HOME",
    "streetNumber" : "100",
    "streetName" : "Bishop Street",
    "suburb" : "Chatswood",
    "postalCode" : "2010",
    "city" : "Sydney",
    "state" : "NSW",
    "country" : "AU"
  } ]
}
----

.Sample response
[source,http,options="nowrap"]
----
HTTP/1.1 201 Created
Content-Type: application/json;charset=UTF-8
Content-Length: 19

{
  "id" : "42"
}
----

=== Update customer 

Update an existing Customer record by customerId in Organisation CRM system.

*PUT /customers/{customerId}*

.Sample request
[source,http,options="nowrap"]
----
PUT /customers/42 HTTP/1.1
Content-Type: application/json;charset=UTF-8
correlationId: 4a34dfd12
Host: localhost:8080
Content-Length: 382

{
  "firstName" : "John",
  "lastName" : "Doe",
  "dateOfBirth" : "1980-12-28",
  "emailAddress" : "johndoe@company.com",
  "postalAddresses" : [ {
    "addressType" : "HOME",
    "streetNumber" : "100",
    "streetName" : "Bishop Street",
    "suburb" : "Chatswood",
    "postalCode" : "2010",
    "city" : "Sydney",
    "state" : "NSW",
    "country" : "AU"
  } ]
}
----

.Sample response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK

----

=== Delete customer

Delete an existing Customer record by customerId in Organisation CRM system.

*DELETE /customers/{customerId}*

.Sample request
[source,http,options="nowrap"]
----
DELETE /customers/42 HTTP/1.1
Content-Type: application/json;charset=UTF-8
correlationId: 4a34dfd12
Host: localhost:8080

----

.Sample response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK

----

== License

The MIT License

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
